name: Build iOS IPA Unsigned

on:
  workflow_dispatch:
  push:
    branches: [ main, master, flutterflow ]

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Fix intl dependency conflict
        run: flutter pub add intl:^0.20.3

      - name: Update Minimum iOS Deployment Target
        run: |
          if [ -f ios/Podfile ]; then
            sed -i '' 's/# platform :ios/platform :ios/' ios/Podfile
            sed -i '' "s/platform :ios, '.*'/platform :ios, '13.0'/" ios/Podfile
            sed -i '' 's/platform :ios, ".*"/platform :ios, "13.0"/' ios/Podfile
          fi

      - name: Get Dependencies
        run: flutter pub get

      - name: Build iOS (Unsigned)
        run: flutter build ios --release --no-codesign

      - name: Package App into .IPA
        run: |
          mkdir -p Payload
          cp -r build/ios/iphoneos/Runner.app Payload/
          zip -r Runner.ipa Payload

      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-ios-runner
          path: Runner.ipa
